name: Node.js Package

on:
    push:
        tags:
            - "v*"

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            packages: read
            contents: read
        env:
            GITHUB_READ_PACKAGES_TOKEN: ${{ github.token }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: project - install
              run: yarn --frozen-lockfile
            - run: yarn eslint

    publish:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        env:
            GITHUB_READ_PACKAGES_TOKEN: ${{ github.token }}
            GITHUB_TOKEN: ${{ github.token }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: https://npm.pkg.github.com/
            - name: project - install
              run: yarn --frozen-lockfile
            - name: test
              run: xvfb-run yarn test --coverage --source-map --verbose || exit 1
            - run: yarn prepare
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
